return function()
  require("indent_blankline").setup({
    char = "│",
    filetype_exclude = {
      "", -- for all buffers without a file type
      "NvimTree",
      "neo-tree",
      "TelescopePrompt",
      "dashboard",
      "dotooagenda",
      "flutterToolsOutline",
      "fugitive",
      "git",
      "gitcommit",
      "help",
      "json",
      "log",
      "markdown",
      "peekaboo",
      "startify",
      "todoist",
      "txt",
      "vimwiki",
      "vista",
      "Trouble"
    },
    buftype_exclude = { "terminal", "nofile", "telescope" },
    context_patterns = {
      "function",
      "if_statement",
      "import",
      "list_literal",
      "selector",
      "type",
      "var",
      "class",
      "method",
      "element",
      "^if",
      "^while",
      "^for",
      "^object",
      "^table",
      "block",
      "arguments",
    },
    space_char_blankline = " ",
    use_treesitter = true,
    show_current_context = true,
    show_current_context_start = false,
    show_end_of_line = false,
    show_trailing_blankline_indent = false,
    -- show_first_indent_level = true,
  })
end
